# Generated by Django 2.1.3 on 2018-12-17 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2018, 12, 17, 9, 21, 19, 199706)),
        ),
    ]
